name: DockerHub CD
on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Java artifact
        working-directory: ./Nueva_carpeta/demo
        run: |
          chmod +x mvnw || true
          ./mvnw -DskipTests clean package
      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          tags: oceansforce684/primer_repo:tagname